name: emergency_response_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9
  flutter_riverpod: ^2.6.1
  location: ^8.0.0
  http: ^1.3.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path: ^1.9.0
  flutter_local_notifications: ^19.3.0
  flutter_svg: ^2.2.0
  hugeicons: ^0.0.10
  cloud_functions: ^5.6.1
  app_links: ^6.4.0
  flutter_background_geolocation: ^4.16.9
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  responsive_framework: ^1.1.1
  google_fonts: ^6.1.0
  go_router: ^15.1.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  supabase_flutter: ^2.9.1
  googleapis_auth: ^2.0.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2

launcher_name:
  default: Era

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/emergency-response-app-dit-firebase-adminsdk-fbsvc-f1e8212865.json
