name: emergency_response_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_riverpod: ^2.6.1
  location: ^8.0.0
  google_maps_flutter: ^2.12.1
  http: ^1.3.0
  uuid: ^4.5.1
  flutter_svg: ^2.1.0
  hugeicons: ^0.0.10
  cloud_functions: ^5.4.0
  app_links: ^6.4.0
  flutter_background_geolocation: ^4.16.9
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  responsive_framework: ^1.1.1
  google_fonts: ^6.1.0
  go_router: ^15.1.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2

launcher_name:
  default: Era


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
